name: Workflow B

on:
  repository_dispatch:
    types: [trigger-workflow-b]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy stuff
        run: echo "🚀 Workflow B triggered via repository_dispatch!"
