name: Notify Slack

on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: echo "Send Slack notification: Build succeeded!"
